kind: ServiceAccount
apiVersion: v1
metadata:
  name: nginx-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-sa
  namespace: CHANGEME
subjects:
  - kind: ServiceAccount
    name: nginx-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
