bases:
- ../../base

nameSuffix: -dev

components:
  - ../../components/serviceaccounts

namespace: nginx-dev

patchesStrategicMerge:
- cpu_count.yaml
- replica_count.yaml

replicas:
  - name: nginx-proxy
    count: 2
