apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  myapp: nginx-proxy
resources:
- deployment.yaml
- service.yaml


configMapGenerator:
- name: conf
  literals:
    - main.conf=|
        color=cornflower_blue
        log_level=info