apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-proxy-svc
  name: nginx-proxy-svc
spec:
  selector:
    app: nginx-proxy-svc
  type: NodePort
status:
  loadBalancer: {}
