apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy-svc
  name: nginx-proxy-svc
spec:
  ports:
  - name: np-http
    port: 38000
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx-proxy
  type: NodePort
status:
  loadBalancer: {}
