---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-proxy-prd
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-svc
  namespace: nginx-proxy-prd
spec:
  ports:
  - name: np-http
    port: 38001
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx-proxy-prd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-proxy-prd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-proxy-prd
  template:
    metadata:
      labels:
        app: nginx-proxy-prd
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

