---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-svc
spec:
  ports:
  - name: np-http
    port: 38123
    targetPort: 8080
    protocol: TCP
  selector:
    app: nginx-proxy-ppd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-proxy-ppd
  template:
    metadata:
      labels:
        app: nginx-proxy-ppd
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-proxy-ppd